export interface Tool {
  id: string;
  name: string;
  description: string;
  route: string;
  icon: string;
  category: string;
  updatedAt: string;
  external?: boolean; // If true, opens in new tab
}

// Ordered from recent organic landing-page performance. Keep this list small so
// the homepage and command palette highlight the same genuinely popular tools.
export const POPULAR_TOOL_IDS = [
  'saml-metadata-parser',
  'stacktrace-formatter',
  'file-size-converter',
  'ios-app-lookup',
  'beautify-stack-trace',
  'random-number-generator',
] as const;

export const TOOLS: Tool[] = [
  {
    id: 'js-tokenizer',
    name: 'JS Tokenizers',
    description: 'Tokenize text using various AI tokenizers',
    route: '/tools/js-tokenizer',
    icon: '🤖',
    category: 'AI Tools',
    updatedAt: '2026-06-28',
  },
  {
    id: 'rag-chunker',
    name: 'RAG Chunker',
    description: 'Split text into retrieval-friendly chunks with overlap and token counts',
    route: '/tools/rag-chunker',
    icon: '🧩',
    category: 'AI Tools',
    updatedAt: '2026-06-28',
  },
  {
    id: 'sentiment-analysis',
    name: 'Sentiment Analysis',
    description: 'Analyze emotional tone of text using AI',
    route: '/tools/sentiment-analysis',
    icon: '😊',
    category: 'AI Tools',
    updatedAt: '2026-06-28',
  },
  {
    id: 'zero-shot-classification',
    name: 'Zero-Shot Classification',
    description: 'Classify text into custom categories without training using AI',
    route: '/tools/zero-shot-classification',
    icon: '🎯',
    category: 'AI Tools',
    updatedAt: '2026-06-28',
  },
  {
    id: 'sentence-similarity',
    name: 'Sentence Similarity',
    description: 'Generate embeddings and find semantic similarity between texts using AI',
    route: '/tools/sentence-similarity',
    icon: '🔍',
    category: 'AI Tools',
    updatedAt: '2026-06-28',
  },
  {
    id: 'question-answering',
    name: 'Question Answering',
    description: 'Answer questions based on provided context using AI',
    route: '/tools/question-answering',
    icon: '❓',
    category: 'AI Tools',
    updatedAt: '2026-06-28',
  },
  {
    id: 'fill-mask',
    name: 'Fill-Mask Text Completion',
    description: 'Complete sentences and predict missing words using AI',
    route: '/tools/fill-mask',
    icon: '✨',
    category: 'AI Tools',
    updatedAt: '2026-06-28',
  },
  {
    id: 'text-summarization',
    name: 'Text Summarization',
    description: 'Summarize long text into concise overviews using AI',
    route: '/tools/text-summarization',
    icon: '📝',
    category: 'AI Tools',
    updatedAt: '2026-06-28',
  },
  {
    id: 'text-extractor',
    name: 'Text Extractor',
    description: 'Extract emails, URLs, IPs, dates, and patterns from text',
    route: '/tools/text-extractor',
    icon: '🔎',
    category: 'AI Tools',
    updatedAt: '2026-06-28',
  },
  {
    id: 'vibe-check',
    name: 'Vibe Check',
    description: 'Generate AI code review, test plan, and production readiness prompts for vibe-coded apps',
    route: '/tools/vibe-check',
    icon: '🧪',
    category: 'AI Tools',
    updatedAt: '2026-06-28',
  },
  {
    id: 'json-prettifier',
    name: 'JSON Prettifier',
    description: 'Format and validate JSON data',
    route: '/tools/json-prettifier',
    icon: '{}',
    category: 'Formatting',
    updatedAt: '2026-07-10',
  },
  {
    id: 'xml-prettifier',
    name: 'XML/HTML Formatter',
    description: 'Format, validate, prettify, and minify XML or HTML data',
    route: '/tools/xml-prettifier',
    icon: '📄',
    category: 'Formatting',
    updatedAt: '2026-07-12',
  },
  {
    id: 'hl7-parser',
    name: 'HL7 Parser',
    description: 'Read and parse HL7 v2 messages into structured JSON',
    route: '/tools/hl7-parser',
    icon: '🏥',
    category: 'Formatting',
    updatedAt: '2026-06-28',
  },
  {
    id: 'hl7-to-fhir',
    name: 'HL7 to FHIR Converter',
    description: 'Convert HL7 v2 messages to FHIR R4 Bundles',
    route: '/tools/hl7-to-fhir',
    icon: '🔄',
    category: 'Formatting',
    updatedAt: '2026-06-28',
  },
  {
    id: 'diff-compare',
    name: 'Diff / Text Compare',
    description: 'Compare two texts and see color-coded differences',
    route: '/tools/diff-compare',
    icon: '📊',
    category: 'Formatting',
    updatedAt: '2026-06-28',
  },
  {
    id: 'stacktrace-formatter',
    name: 'Stack Trace Formatter',
    description: 'Format and beautify JavaScript, Python, Java, C#, Go, PHP, and Ruby stack traces',
    route: '/tools/stacktrace-formatter',
    icon: '📋',
    category: 'Formatting',
    updatedAt: '2026-06-28',
  },
  {
    id: 'beautify-stack-trace',
    name: 'Beautify Stack Trace',
    description: 'Clean up and beautify messy error stack traces for readability',
    route: '/tools/beautify-stack-trace',
    icon: '✨',
    category: 'Formatting',
    updatedAt: '2026-06-28',
  },
  {
    id: 'stacktrace-analyzer',
    name: 'Stack Trace Analyzer',
    description: 'Analyze stack traces to identify root causes, explain errors, and separate app from framework code',
    route: '/tools/stacktrace-analyzer',
    icon: '🔬',
    category: 'Formatting',
    updatedAt: '2026-06-28',
  },
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings',
    route: '/tools/base64-encoder',
    icon: '🔤',
    category: 'Formatting',
    updatedAt: '2026-07-10',
  },
  {
    id: 'file-size-converter',
    name: 'File Size Converter',
    description: 'Convert file sizes between decimal (SI) and binary (IEC) units',
    route: '/tools/file-size-converter',
    icon: '💾',
    category: 'Formatting',
    updatedAt: '2026-06-28',
  },
  {
    id: 'unix-timestamp',
    name: 'Unix Timestamp Converter',
    description: 'Convert Unix epoch timestamps to human-readable dates — single or batch — with timezone support',
    route: '/tools/unix-timestamp',
    icon: '⏱️',
    category: 'Formatting',
    updatedAt: '2026-07-12',
  },
  {
    id: 'cron-tester',
    name: 'Cron Expression Tester',
    description: 'Test and parse cron expressions, explain them in plain English, and preview upcoming run times across timezones',
    route: '/tools/cron-tester',
    icon: '⏰',
    category: 'Formatting',
    updatedAt: '2026-07-10',
  },
  {
    id: 'cron-generator',
    name: 'Cron Expression Generator',
    description: 'Build cron expressions visually with field controls — no syntax knowledge required',
    route: '/tools/cron-generator',
    icon: '🛠️',
    category: 'Formatting',
    updatedAt: '2026-06-28',
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder / Decoder',
    description: 'Encode and decode URLs using encodeURIComponent and encodeURI',
    route: '/tools/url-encoder',
    icon: '🔗',
    category: 'Formatting',
    updatedAt: '2026-06-28',
  },
  {
    id: 'yaml-json-converter',
    name: 'YAML/JSON Converter & Formatter',
    description: 'Convert between YAML and JSON, or format and validate standalone YAML',
    route: '/tools/yaml-json-converter',
    icon: '🔄',
    category: 'Formatting',
    updatedAt: '2026-07-12',
  },
  {
    id: 'csv-json-converter',
    name: 'CSV ↔ JSON Converter',
    description: 'Convert between CSV and JSON with auto-detection, delimiter handling, type inference, and nested-object flattening',
    route: '/tools/csv-json-converter',
    icon: '🔄',
    category: 'Formatting',
    updatedAt: '2026-06-28',
  },
  {
    id: 'csv-viewer',
    name: 'CSV Viewer / Table Explorer',
    description: 'Paste CSV and explore it as a sortable, searchable table with sticky headers — no spreadsheet required',
    route: '/tools/csv-viewer',
    icon: '🔍',
    category: 'Formatting',
    updatedAt: '2026-06-28',
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and prettify SQL queries with support for MySQL, PostgreSQL, SQLite, and more',
    route: '/tools/sql-formatter',
    icon: '🗄️',
    category: 'Formatting',
    updatedAt: '2026-07-10',
  },
  {
    id: 'string-similarity',
    name: 'String Similarity',
    description: 'Compare strings using Jaro-Winkler, Levenshtein, Dice, and Hamming algorithms',
    route: '/tools/string-similarity',
    icon: '🔀',
    category: 'Algorithms',
    updatedAt: '2026-06-28',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with match highlighting, capture groups, and string replacement',
    route: '/tools/regex-tester',
    icon: '🔍',
    category: 'Algorithms',
    updatedAt: '2026-07-10',
  },
  {
    id: 'regex-library',
    name: 'Regex Library',
    description: 'Browse and copy common regular expressions for validation, extraction, and text processing',
    route: '/tools/regex-library',
    icon: '📚',
    category: 'Algorithms',
    updatedAt: '2026-06-28',
  },
  {
    id: 'number-base-converter',
    name: 'Number Base Converter',
    description: "Convert numbers between binary, octal, decimal, and hex with two's complement",
    route: '/tools/number-base-converter',
    icon: '🔢',
    category: 'Algorithms',
    updatedAt: '2026-06-28',
  },
  {
    id: 'semver-comparator',
    name: 'SemVer Comparator',
    description: 'Compare, sort, and validate semantic version strings per SemVer 2.0.0 with prerelease and build metadata support',
    route: '/tools/semver-comparator',
    icon: '⚖️',
    category: 'Algorithms',
    updatedAt: '2026-07-12',
  },
  {
    id: 'ios-app-lookup',
    name: 'iOS App Lookup',
    description: 'Look up iOS app metadata from the App Store using bundle ID',
    route: '/tools/ios-app-lookup',
    icon: '🍎',
    category: 'Apps',
    updatedAt: '2026-06-28',
  },
  {
    id: 'gamewobble',
    name: 'GameWobble',
    description: 'Free bite-sized browser games you can play instantly with no downloads or signup',
    route: 'https://gamewobble.com',
    icon: '🎮',
    category: 'Apps',
    updatedAt: '2026-06-29',
    external: true,
  },
  {
    id: 'terremoto',
    name: 'Terremoto',
    description: 'iOS app for tracking earthquakes in real-time',
    route: 'https://terremoto.developers.do',
    icon: '🌍',
    category: 'Apps',
    updatedAt: '2026-06-28',
    external: true,
  },
  {
    id: 'fedpulse',
    name: 'FedPulse',
    description: 'iOS app to search, save, and track federal government jobs',
    route: 'https://fedpulse.developers.do',
    icon: '🏛️',
    category: 'Apps',
    updatedAt: '2026-06-28',
    external: true,
  },
  {
    id: 'part107-quiz-prep',
    name: 'FAA Part 107 Quiz Prep',
    description: 'iOS app for FAA Part 107 drone pilot certification exam preparation',
    route: 'https://part107.developers.do',
    icon: '🚁',
    category: 'Apps',
    updatedAt: '2026-06-28',
    external: true,
  },
  {
    id: 'citizenship-test-prep',
    name: 'Citizenship Test Prep',
    description: 'iOS app for US citizenship naturalization test preparation',
    route: 'https://citizenshiptest.developers.do',
    icon: '🇺🇸',
    category: 'Apps',
    updatedAt: '2026-06-28',
    external: true,
  },
  {
    id: 'clawpet',
    name: 'ClawPet',
    description: 'iOS virtual desktop pet that visualizes bot activity in real-time',
    route: 'https://clawpet.clawpantry.com',
    icon: '🦀',
    category: 'Apps',
    updatedAt: '2026-06-28',
    external: true,
  },
  {
    id: 'tech-interview-prep',
    name: 'Tech - Interview Prep',
    description: 'iOS app for technical interview prep with 1,400+ questions across AI, system design, and more',
    route: 'https://apps.apple.com/us/app/tech-interview-prep/id6785688459',
    icon: '💻',
    category: 'Apps',
    updatedAt: '2026-07-11',
    external: true,
  },
  {
    id: 'downrangehq-shot-timer',
    name: 'DownRangeHQ Shot Timer',
    description: 'iOS and Apple Watch shot timer and drill tracker for competition shooters',
    route: 'https://apps.apple.com/us/app/downrangehq-shot-timer/id6783020376',
    icon: '🎯',
    category: 'Apps',
    updatedAt: '2026-07-11',
    external: true,
  },
  {
    id: 'melody-island',
    name: 'Melody Island: Kids Piano',
    description: 'iOS piano app for kids with colorful keys, adventure levels, and guided songs',
    route: 'https://apps.apple.com/us/app/melody-island-kids-piano/id6785279265',
    icon: '🎵',
    category: 'Apps',
    updatedAt: '2026-07-11',
    external: true,
  },
  {
    id: 'colorpop-calculator',
    name: 'ColorPop Calculator',
    description: 'iOS calculator for kids ages 4-8 with visual object-based math',
    route: 'https://apps.apple.com/us/app/colorpop-calculator/id6785313208',
    icon: '🧮',
    category: 'Apps',
    updatedAt: '2026-07-11',
    external: true,
  },
  {
    id: 'phlebotomy-exam-prep',
    name: 'Phlebotomy Technician ExamPrep',
    description: 'iOS app for NHA Certified Phlebotomy Technician exam preparation',
    route: 'https://apps.apple.com/us/app/phlebotomy-technician-examprep/id6758586662',
    icon: '💉',
    category: 'Apps',
    updatedAt: '2026-07-11',
    external: true,
  },
  {
    id: 'ccma-exam-prep',
    name: 'CCMA Exam Prep',
    description: 'iOS app for Certified Clinical Medical Assistant exam preparation',
    route: 'https://apps.apple.com/us/app/ccma-exam-prep/id6758587083',
    icon: '🩺',
    category: 'Apps',
    updatedAt: '2026-07-11',
    external: true,
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure random passwords',
    route: '/tools/password-generator',
    icon: '🔑',
    category: 'Generators',
    updatedAt: '2026-06-28',
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUIDs across all RFC 9562 versions — nil, v1, v2, v3, v4, v5, v6, v7, and v8',
    route: '/tools/uuid-generator',
    icon: '🆔',
    category: 'Generators',
    updatedAt: '2026-07-12',
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text for designs',
    route: '/tools/lorem-ipsum-generator',
    icon: '📄',
    category: 'Generators',
    updatedAt: '2026-06-28',
  },
  {
    id: 'random-number-generator',
    name: 'Random Number Generator',
    description: 'Generate random numbers and see code samples in multiple languages',
    route: '/tools/random-number-generator',
    icon: '🎲',
    category: 'Generators',
    updatedAt: '2026-06-28',
  },
  {
    id: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text, URLs, or any data',
    route: '/tools/qr-code-generator',
    icon: '📱',
    category: 'Generators',
    updatedAt: '2026-06-28',
  },
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript',
    description: 'Convert JSON to TypeScript interfaces',
    route: '/tools/json-to-typescript',
    icon: '📝',
    category: 'Code & Schemas',
    updatedAt: '2026-06-28',
  },
  {
    id: 'json-to-jsdoc',
    name: 'JSON to JSDoc',
    description: 'Convert JSON to JSDoc type definitions',
    route: '/tools/json-to-jsdoc',
    icon: '📜',
    category: 'Code & Schemas',
    updatedAt: '2026-06-28',
  },
  {
    id: 'json-to-csharp',
    name: 'JSON to C#',
    description: 'Convert JSON to C# classes',
    route: '/tools/json-to-csharp',
    icon: '💎',
    category: 'Code & Schemas',
    updatedAt: '2026-06-28',
  },
  {
    id: 'json-to-swift',
    name: 'JSON to Swift',
    description: 'Convert JSON to Swift structs',
    route: '/tools/json-to-swift',
    icon: '🍎',
    category: 'Code & Schemas',
    updatedAt: '2026-06-28',
  },
  {
    id: 'json-to-kotlin',
    name: 'JSON to Kotlin',
    description: 'Convert JSON to Kotlin data classes',
    route: '/tools/json-to-kotlin',
    icon: '🟣',
    category: 'Code & Schemas',
    updatedAt: '2026-06-28',
  },
  {
    id: 'json-to-python',
    name: 'JSON to Python',
    description: 'Convert JSON to Python dataclasses or Pydantic models',
    route: '/tools/json-to-python',
    icon: '🐍',
    category: 'Code & Schemas',
    updatedAt: '2026-06-28',
  },
  {
    id: 'json-to-go',
    name: 'JSON to Go',
    description: 'Convert JSON to Go structs',
    route: '/tools/json-to-go',
    icon: '🐹',
    category: 'Code & Schemas',
    updatedAt: '2026-06-28',
  },
  {
    id: 'json-to-rust',
    name: 'JSON to Rust',
    description: 'Convert JSON to Rust structs',
    route: '/tools/json-to-rust',
    icon: '🦀',
    category: 'Code & Schemas',
    updatedAt: '2026-06-28',
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    description: 'Pick colors, convert between HEX/RGB/HSL/HSV/CMYK, and browse curated palettes (Tailwind, Nord, Solarized, Dracula, and more)',
    route: '/tools/color-picker',
    icon: '🎨',
    category: 'Code & Schemas',
    updatedAt: '2026-07-12',
  },
  {
    id: 'secrets-scanner',
    name: 'Secrets Scanner',
    description: 'Scan text, logs, or configs for leaked keys and tokens',
    route: '/tools/secrets-scanner',
    icon: '🛡️',
    category: 'Security',
    updatedAt: '2026-06-28',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JWT tokens',
    route: '/tools/jwt-decoder',
    icon: '🔓',
    category: 'Security',
    updatedAt: '2026-07-10',
  },
  {
    id: 'md5-generator',
    name: 'MD5 Hash',
    description: 'Generate MD5 hashes from text',
    route: '/tools/md5-generator',
    icon: '#️⃣',
    category: 'Security',
    updatedAt: '2026-06-28',
  },
  {
    id: 'sha1-generator',
    name: 'SHA-1 Hash',
    description: 'Generate SHA-1 hashes from text',
    route: '/tools/sha1-generator',
    icon: '🔐',
    category: 'Security',
    updatedAt: '2026-06-28',
  },
  {
    id: 'sha256-generator',
    name: 'SHA-256/384/512 Hash',
    description: 'Generate secure SHA-256, SHA-384, or SHA-512 hashes from text',
    route: '/tools/sha256-generator',
    icon: '🔒',
    category: 'Security',
    updatedAt: '2026-07-12',
  },
  {
    id: 'clawdbot-security-scanner',
    name: 'Clawdbot Security Scanner',
    description: 'Audit Clawdbot/Moltbot/OpenClaw configs for security vulnerabilities',
    route: '/tools/clawdbot-security-scanner',
    icon: '🤖',
    category: 'Security',
    updatedAt: '2026-06-28',
  },
  {
    id: 'saml-decoder',
    name: 'SAML Decoder',
    description: 'Decode SAML Requests/Responses from Base64 to readable XML',
    route: '/tools/saml-decoder',
    icon: '🔏',
    category: 'SAML',
    updatedAt: '2026-07-10',
  },
  {
    id: 'saml-metadata-parser',
    name: 'SAML Metadata Parser',
    description: 'Parse SAML Metadata XML and extract IdP/SP configuration',
    route: '/tools/saml-metadata-parser',
    icon: '📋',
    category: 'SAML',
    updatedAt: '2026-06-28',
  },
  {
    id: 'saml-cert-inspector',
    name: 'SAML Certificate Inspector',
    description: 'Inspect X.509 certificates from SAML metadata, responses, or PEM',
    route: '/tools/saml-cert-inspector',
    icon: '📜',
    category: 'SAML',
    updatedAt: '2026-06-28',
  },
  {
    id: 'csr-decoder',
    name: 'Certificate & CSR Decoder',
    description: 'Decode X.509 certificates and PKCS#10 CSRs — subject, issuer, expiry, SANs, extensions, and key details',
    route: '/tools/csr-decoder',
    icon: '📄',
    category: 'Security',
    updatedAt: '2026-06-28',
  },
  {
    id: 'saml-builder',
    name: 'SAML Assertion Builder',
    description: 'Generate test SAML Responses, AuthnRequests, and LogoutRequests',
    route: '/tools/saml-builder',
    icon: '🏗️',
    category: 'SAML',
    updatedAt: '2026-06-28',
  },
  {
    id: 'saml-metadata-generator',
    name: 'SAML Metadata Generator',
    description: 'Generate SAML 2.0 EntityDescriptor metadata XML for SPs and IdPs',
    route: '/tools/saml-metadata-generator',
    icon: '🪪',
    category: 'SAML',
    updatedAt: '2026-06-28',
  },
  {
    id: 'saml-validator',
    name: 'SAML Response Validator',
    description: 'Debug a SAML Response and find out why SSO login is failing',
    route: '/tools/saml-validator',
    icon: '🚦',
    category: 'SAML',
    updatedAt: '2026-06-28',
  },
  {
    id: 'api-tester',
    name: 'API Tester',
    description: 'Test and view API responses',
    route: '/tools/api-tester',
    icon: '🌐',
    category: 'Networking',
    updatedAt: '2026-06-28',
  },
  {
    id: 'http-status-codes',
    name: 'HTTP Status Code Reference',
    description: 'Searchable reference of all HTTP status codes with descriptions and use cases',
    route: '/tools/http-status-codes',
    icon: '📡',
    category: 'Networking',
    updatedAt: '2026-06-28',
  },
  {
    id: 'oss-data',
    name: 'OSS Data',
    description: 'Open-source data tools for developers',
    route: 'https://data.developers.do',
    icon: '📊',
    category: 'Data',
    updatedAt: '2026-06-28',
    external: true,
  },
];
